---
- hosts: localhost
  gather_facts: False
  connection: local
  become: True

  
  tasks:
  - name: install packages
    package:
      name:
        - htop
        - tmux

  - name: copy file
    copy:
      src: files/test.txt
      dest: /home/bo/Dokumente/testnachansible.txt
      owner: bo
      group: bo
...
