---
- hosts: localhost
  gather_facts: False
  connection: local
  become: True

  
  vars: 
    ansible_python_interpreter: /usr/bin/python3
    ansible_user: bo
    
  tasks:
  - name: install packages
    package:
      name:
        - htop
        - tmux

  - name: copy file
    copy:
      src: files/test.txt
      dest: /home/bo/Dokumente/testnachansible.txt
      owner: bo
      group: bo

...
